export const SAMPLE_CARDS = [
	{
		uuid: "card-uuid-001",
		name: "Lightning Bolt",
		asciiName: "Lightning Bolt",
		faceName: null,
		type: "Instant",
		types: ["Instant"],
		subtypes: [],
		supertypes: [],
		colors: ["R"],
		colorIdentity: ["R"],
		colorIndicator: null,
		producedMana: null,
		manaCost: "{R}",
		text: "Lightning Bolt deals 3 damage to any target.",
		layout: "normal",
		side: null,
		power: null,
		toughness: null,
		loyalty: null,
		keywords: null,
		identifiers: {},
		isFunny: null,
		edhrecSaltiness: null,
		subsets: null,
		manaValue: 1.0,
		faceManaValue: null,
		defense: null,
		hand: null,
		life: null,
		edhrecRank: 5,
		legalities: {},
		leadershipSkills: null,
		rulings: null,
		hasAlternativeDeckLimit: null,
		isReserved: null,
		isGameChanger: null,
		printings: ["A25", "2ED", "3ED", "M10", "M11"],
		purchaseUrls: {},
		relatedCards: null,
		setCode: "A25",
		number: "141",
		artist: "Christopher Moeller",
		artistIds: null,
		borderColor: "black",
		frameVersion: "2015",
		frameEffects: null,
		watermark: null,
		signature: null,
		securityStamp: null,
		flavorText: null,
		flavorName: null,
		faceFlavorName: null,
		originalText: "Lightning Bolt deals 3 damage to any target.",
		originalType: "Instant",
		printedName: null,
		printedText: null,
		printedType: null,
		facePrintedName: null,
		availability: ["paper", "mtgo"],
		boosterTypes: null,
		finishes: ["nonfoil", "foil"],
		promoTypes: null,
		attractionLights: null,
		isFullArt: null,
		isOnlineOnly: null,
		isOversized: null,
		isPromo: null,
		isReprint: true,
		isTextless: null,
		otherFaceIds: null,
		cardParts: null,
		language: "English",
		sourceProducts: null,
		rarity: "uncommon",
		duelDeck: null,
		isRebalanced: null,
		originalPrintings: null,
		rebalancedPrintings: null,
		originalReleaseDate: null,
		isAlternative: null,
		isStorySpotlight: null,
		isTimeshifted: null,
		hasContentWarning: null,
		variations: null,
		foreignData: null,
		releaseDate: "2018-03-16",
	},
	{
		uuid: "card-uuid-002",
		name: "Counterspell",
		asciiName: "Counterspell",
		faceName: null,
		type: "Instant",
		types: ["Instant"],
		subtypes: [],
		supertypes: [],
		colors: ["U"],
		colorIdentity: ["U"],
		colorIndicator: null,
		producedMana: null,
		manaCost: "{U}{U}",
		text: "Counter target spell.",
		layout: "normal",
		side: null,
		power: null,
		toughness: null,
		loyalty: null,
		keywords: null,
		identifiers: {},
		isFunny: null,
		edhrecSaltiness: 1.5,
		subsets: null,
		manaValue: 2.0,
		faceManaValue: null,
		defense: null,
		hand: null,
		life: null,
		edhrecRank: 10,
		legalities: {},
		leadershipSkills: null,
		rulings: null,
		hasAlternativeDeckLimit: null,
		isReserved: null,
		isGameChanger: null,
		printings: ["MH2", "A25"],
		purchaseUrls: {},
		relatedCards: null,
		setCode: "MH2",
		number: "267",
		artist: "Zack Stella",
		artistIds: null,
		borderColor: "black",
		frameVersion: "2015",
		frameEffects: null,
		watermark: null,
		signature: null,
		securityStamp: null,
		flavorText: null,
		flavorName: null,
		faceFlavorName: null,
		originalText: "Counter target spell.",
		originalType: "Instant",
		printedName: null,
		printedText: null,
		printedType: null,
		facePrintedName: null,
		availability: ["paper", "mtgo"],
		boosterTypes: null,
		finishes: ["nonfoil", "foil"],
		promoTypes: null,
		attractionLights: null,
		isFullArt: null,
		isOnlineOnly: null,
		isOversized: null,
		isPromo: null,
		isReprint: true,
		isTextless: null,
		otherFaceIds: null,
		cardParts: null,
		language: "English",
		sourceProducts: null,
		rarity: "uncommon",
		duelDeck: null,
		isRebalanced: null,
		originalPrintings: null,
		rebalancedPrintings: null,
		originalReleaseDate: null,
		isAlternative: null,
		isStorySpotlight: null,
		isTimeshifted: null,
		hasContentWarning: null,
		variations: null,
		foreignData: null,
		releaseDate: "2021-06-18",
	},
	{
		uuid: "card-uuid-003",
		name: "Fire // Ice",
		asciiName: "Fire // Ice",
		faceName: "Fire",
		type: "Instant",
		types: ["Instant"],
		subtypes: [],
		supertypes: [],
		colors: ["R"],
		colorIdentity: ["R", "U"],
		colorIndicator: null,
		producedMana: null,
		manaCost: "{1}{R}",
		text: "Fire deals 2 damage divided as you choose among one or two targets.",
		layout: "split",
		side: "a",
		power: null,
		toughness: null,
		loyalty: null,
		keywords: null,
		identifiers: {},
		isFunny: null,
		edhrecSaltiness: null,
		subsets: null,
		manaValue: 4.0,
		faceManaValue: 2.0,
		defense: null,
		hand: null,
		life: null,
		edhrecRank: 100,
		legalities: {},
		leadershipSkills: null,
		rulings: null,
		hasAlternativeDeckLimit: null,
		isReserved: null,
		isGameChanger: null,
		printings: ["A25"],
		purchaseUrls: {},
		relatedCards: null,
		setCode: "A25",
		number: "223a",
		artist: "Dan Scott",
		artistIds: null,
		borderColor: "black",
		frameVersion: "2015",
		frameEffects: null,
		watermark: null,
		signature: null,
		securityStamp: null,
		flavorText: null,
		flavorName: null,
		faceFlavorName: null,
		originalText: null,
		originalType: null,
		printedName: null,
		printedText: null,
		printedType: null,
		facePrintedName: null,
		availability: ["paper", "mtgo"],
		boosterTypes: null,
		finishes: ["nonfoil"],
		promoTypes: null,
		attractionLights: null,
		isFullArt: null,
		isOnlineOnly: null,
		isOversized: null,
		isPromo: null,
		isReprint: true,
		isTextless: null,
		otherFaceIds: ["card-uuid-004"],
		cardParts: null,
		language: "English",
		sourceProducts: null,
		rarity: "uncommon",
		duelDeck: null,
		isRebalanced: null,
		originalPrintings: null,
		rebalancedPrintings: null,
		originalReleaseDate: null,
		isAlternative: null,
		isStorySpotlight: null,
		isTimeshifted: null,
		hasContentWarning: null,
		variations: null,
		foreignData: null,
		releaseDate: "2018-03-16",
	},
];

export const SAMPLE_SETS = [
	{
		code: "A25",
		name: "Masters 25",
		type: "masters",
		releaseDate: "2018-03-16",
		baseSetSize: 249,
		totalSetSize: 249,
		keyruneCode: "A25",
		translations: {},
		block: null,
		parentCode: null,
		mtgoCode: "A25",
		tokenSetCode: null,
		mcmId: null,
		mcmIdExtras: null,
		mcmName: null,
		tcgplayerGroupId: null,
		cardsphereSetId: null,
		isFoilOnly: false,
		isNonFoilOnly: null,
		isOnlineOnly: false,
		isPaperOnly: null,
		isForeignOnly: null,
		isPartialPreview: null,
		languages: ["English"],
		sealedProduct: [
			{
				uuid: "sealed-uuid-001",
				name: "Masters 25 Booster Box",
				category: "booster_box",
				subtype: null,
				purchaseUrls: {},
				releaseDate: "2018-03-16",
			},
			{
				uuid: "sealed-uuid-002",
				name: "Masters 25 Booster Pack",
				category: "booster_pack",
				subtype: null,
				purchaseUrls: {},
				releaseDate: "2018-03-16",
			},
		],
		booster: null,
	},
	{
		code: "MH2",
		name: "Modern Horizons 2",
		type: "draft_innovation",
		releaseDate: "2021-06-18",
		baseSetSize: 303,
		totalSetSize: 531,
		keyruneCode: "MH2",
		translations: {},
		block: null,
		parentCode: null,
		mtgoCode: "MH2",
		tokenSetCode: null,
		mcmId: null,
		mcmIdExtras: null,
		mcmName: null,
		tcgplayerGroupId: null,
		cardsphereSetId: null,
		isFoilOnly: false,
		isNonFoilOnly: null,
		isOnlineOnly: false,
		isPaperOnly: null,
		isForeignOnly: null,
		isPartialPreview: null,
		languages: ["English"],
		sealedProduct: [
			{
				uuid: "sealed-uuid-003",
				name: "MH2 Set Booster Box",
				category: "booster_box",
				subtype: null,
				purchaseUrls: {},
				releaseDate: "2021-06-18",
			},
		],
		booster: null,
	},
];

export const SAMPLE_TOKENS = [
	{
		uuid: "token-uuid-001",
		name: "Soldier Token",
		asciiName: "Soldier Token",
		faceName: null,
		type: "Token Creature \u2014 Soldier",
		types: ["Token", "Creature"],
		subtypes: ["Soldier"],
		supertypes: [],
		colors: ["W"],
		colorIdentity: ["W"],
		colorIndicator: null,
		producedMana: null,
		manaCost: null,
		text: null,
		layout: "token",
		side: null,
		power: "1",
		toughness: "1",
		loyalty: null,
		keywords: null,
		identifiers: {},
		setCode: "A25",
		number: "T1",
		artist: "Zack Stella",
		artistIds: null,
		borderColor: "black",
		frameVersion: "2015",
		frameEffects: null,
		watermark: null,
		signature: null,
		securityStamp: null,
		flavorText: null,
		flavorName: null,
		availability: ["paper"],
		finishes: ["nonfoil"],
		promoTypes: null,
		isFullArt: null,
		isOnlineOnly: null,
		isPromo: null,
		isReprint: null,
		isTextless: null,
		language: "English",
		releaseDate: "2018-03-16",
		reverseRelated: null,
		relatedCards: null,
	},
	{
		uuid: "token-uuid-002",
		name: "Beast Token",
		asciiName: "Beast Token",
		faceName: null,
		type: "Token Creature \u2014 Beast",
		types: ["Token", "Creature"],
		subtypes: ["Beast"],
		supertypes: [],
		colors: ["G"],
		colorIdentity: ["G"],
		colorIndicator: null,
		producedMana: null,
		manaCost: null,
		text: null,
		layout: "token",
		side: null,
		power: "3",
		toughness: "3",
		loyalty: null,
		keywords: null,
		identifiers: {},
		setCode: "MH2",
		number: "T2",
		artist: "Jason Rainville",
		artistIds: null,
		borderColor: "black",
		frameVersion: "2015",
		frameEffects: null,
		watermark: null,
		signature: null,
		securityStamp: null,
		flavorText: null,
		flavorName: null,
		availability: ["paper"],
		finishes: ["nonfoil"],
		promoTypes: null,
		isFullArt: null,
		isOnlineOnly: null,
		isPromo: null,
		isReprint: null,
		isTextless: null,
		language: "English",
		releaseDate: "2021-06-18",
		reverseRelated: null,
		relatedCards: null,
	},
];

export const SAMPLE_IDENTIFIERS = [
	{
		uuid: "card-uuid-001",
		scryfallId: "scryfall-001",
		scryfallOracleId: "oracle-001",
		scryfallIllustrationId: "illust-001",
		tcgplayerProductId: "12345",
		tcgplayerEtchedProductId: null,
		mtgoId: "mtgo-001",
		mtgoFoilId: "mtgo-foil-001",
		mtgArenaId: "arena-001",
		multiverseId: "442130",
		mcmId: "mcm-001",
		mcmMetaId: "mcm-meta-001",
		cardKingdomId: "ck-001",
		cardKingdomFoilId: "ck-foil-001",
		cardKingdomEtchedId: null,
		cardsphereId: "cs-001",
		cardsphereFoilId: "cs-foil-001",
	},
	{
		uuid: "card-uuid-002",
		scryfallId: "scryfall-002",
		scryfallOracleId: "oracle-002",
		scryfallIllustrationId: "illust-002",
		tcgplayerProductId: "67890",
		tcgplayerEtchedProductId: null,
		mtgoId: "mtgo-002",
		mtgoFoilId: null,
		mtgArenaId: "arena-002",
		multiverseId: "522205",
		mcmId: "mcm-002",
		mcmMetaId: null,
		cardKingdomId: "ck-002",
		cardKingdomFoilId: null,
		cardKingdomEtchedId: null,
		cardsphereId: null,
		cardsphereFoilId: null,
	},
];

export const SAMPLE_FOREIGN_DATA = [
	{
		uuid: "card-uuid-001",
		name: "Blitzschlag",
		language: "German",
		text: "Der Blitzschlag f\u00fcgt einem Ziel deiner Wahl 3 Schadenspunkte zu.",
		type: "Spontanzauber",
		faceName: null,
		flavorText: null,
		multiverseId: null,
	},
	{
		uuid: "card-uuid-001",
		name: "Foudre",
		language: "French",
		text: "La Foudre inflige 3 blessures \u00e0 n'importe quelle cible.",
		type: "\u00c9ph\u00e9m\u00e8re",
		faceName: null,
		flavorText: null,
		multiverseId: null,
	},
	{
		uuid: "card-uuid-002",
		name: "Contresort",
		language: "French",
		text: "Contrecarrez le sort cibl\u00e9.",
		type: "\u00c9ph\u00e9m\u00e8re",
		faceName: null,
		flavorText: null,
		multiverseId: null,
	},
];

export const SAMPLE_LEGALITIES = [
	{ uuid: "card-uuid-001", format: "modern", status: "Legal" },
	{ uuid: "card-uuid-001", format: "legacy", status: "Legal" },
	{ uuid: "card-uuid-001", format: "vintage", status: "Restricted" },
	{ uuid: "card-uuid-001", format: "standard", status: "Not Legal" },
	{ uuid: "card-uuid-002", format: "modern", status: "Legal" },
	{ uuid: "card-uuid-002", format: "legacy", status: "Legal" },
	{ uuid: "card-uuid-002", format: "vintage", status: "Legal" },
	{ uuid: "card-uuid-002", format: "standard", status: "Not Legal" },
	{ uuid: "card-uuid-002", format: "historic", status: "Suspended" },
];
